server:
  port: 8086

spring:
  application:
    name: payment-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: paymentdb

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
