create table tbl_passenger (
        id integer generated by default as identity,
        mobile bigint unique,
        pass_name varchar(50) not null,
        email varchar(255) unique,
        gender varchar(255),
        primary key (id)
    );