apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels: { app: booking }
    spec:
      containers:
      - name: booking
        image: syskantechnosoft/booking-service:latest
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongo:27017/bookingdb
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8085
  type: ClusterIP
