create table users (
	ID INT,
	USERNAME VARCHAR(50),
	HASHED_PASSWORD VARCHAR(250),
	EMAIL VARCHAR(50),	
	MOBILE VARCHAR(50),
	CREATED_AT DATE,
	CREATED_BY INT,	
	UPDATED_AT DATE,
	UPDATED_BY INT
);